export const CHECKLIST_SECTIONS = {
    PRE_SERVICE: [
        {
            id: "check_en_service",
            title: "Check List En Service",
            items: [
                "UNIDAD DE ORDEÑE:",
                "Pezoneras correspondientes + 2 paquetes repuesto",
                "Tubos cortos correspondientes + 8 respuesto",
                "Repuestos de colector (garra)",
                "2 casquillos de repuesto",
                "SISTEMA DE LAVADO:",
                "Copas de lavado -  lavador de pezonera",
                "Distribuidor de lavado",
                "Velas - jettr de lavado (según tambo)",
                "PULSADO:",
                "Kit reparacion de pulsadores correspondiente",
                "Pulsador completo",
                "REGULACION:",
                "Kit reparacion de regulador de vacio",
                "Regulador de vacio completo de repuesto",
                "Acoples en pvc para colocar regulador",
                "BOMBA DE LECHE:",
                "Sello bomba de leche",
                "Tapa intermedia",
                "Guarnicion",
                "Turbina",
                "Eje",
                "Pico de salida",
                "BOMBA DE VACIO:",
                "Valvula antiretorno para bomba de vacio 75 pvc",
                "EXTRACTOR:",
                "Piola para extractor (según tambo)",
                "Gancho para extractor (según tambo)",
                "Kit de reparacion para valvula extractor (según tambo)",
                "Diafragma de valvula de corte",
                "REPUESTOS VARIOS:",
                "Valvula de drenaje 3/4 amarilla",
                "Vacuometro",
                "Montura para valvula - vacuometro",
                "Aplicador de sellador",
                "Dispositivo lava ubre (lava tetas)",
                "Paquete de esponja x 3",
                "Accesorios goma (cupla - codo - reducciones)",
                "Abrazaderas para accesoriso de goma",
                "Paquete de filtros (segun tambo)",
                "MAQUINARIA INDISPENSABLE:",
                "Pulsografo",
                "Arco de sierra",
                "Llave 13 y 14",
                "Atornillador dewalt",
            ]
        },
        {
            id: "comederos",
            title: "Comederos",
            items: [
                "Sinfín flexible",
                "Sinfín rigido",
                "Eje para sinfín rigido",
                "Caño 90 pvc",
                "Caño 90 chapa",
                "Curva de llenado 90 pvc",
                "Mando doble bolillero tellmak",
                "Traba para mandos",
                "Parrilla para motor 1 hp",
                "Parrilla para motor 2 hp",
                "Grampa 90 chica",
                "Grampa 90 grande",
                "Bulon con tuerca 5/16\"",
                "Bulon con tuerca 3/8\"",
                "Hierro angulo",
                "Motor 1 hp",
                "Motor 2 hp",
                "Polea motor 1hp",
                "Polea motor 2hp",
                "Polea para mando",
                "Prisioneros",
                "Correas b",
                "Tee de llevado",
                "Final de carrera",
                "Contactor",
                "Relevo termico",
                "Timer gt3a",
                "Zocalo para timer",
                "Boton schneider",
                "Maneta schneider",
                "Recorte chapa galva del 18",
                "Reductora de dosificacion (según tambo)",
                "MAQUINARIA INDISPENSABLE:",
                "Soldadora - careta - electrodo",
                "Dewalt - copas",
                "Atornillador",
                "Juego de tubos",
                "Stilson",
                "Amoladora - discos",
            ]
        },
        {
            id: "equipo_frio",
            title: "Equipo Frio",
            items: [
                "PARTE ELECTRICA:",
                "Contactor",
                "Relevo termico",
                "Termica",
                "Cable unipolar 4 mm - 6 mm",
                "Plaqueta frente bauducco",
                "Plaqueta fondo bauducco",
                "Etc-200 con zonda",
                "PARTE AGITADOR:",
                "Agitador completo (según tambo)",
                "Estator",
                "Rotor",
                "Capacitor",
                "Caja de conecciones",
                "Chaveta de inox",
                "Tandem de bolilleros",
                "PARTE UNIDAD CONDENSADORA:",
                "Forzador (según tambo)",
                "Compresor",
                "Valvulas de servicio de compresor",
                "Presostato de alta - baja automatico",
                "Presostato de alta automatico",
                "Presostato de baja automatico",
                "Gas refrigerante (según tambo)",
                "Filtro molecular (segun tambo)",
                "Valvula expansion danfoss con compensador",
                "Toberas",
                "Tuercas de bronce",
                "Accesorios de cobre (codo - cupla - tee)",
                "Varilla de plata",
                "Decapante",
                "Caños de cobre",
                "PARTE LAVADO:",
                "Bomba peristaltica",
                "Rotor de bomba peristaltica",
                "Cartucho de silicona bomba peristatica",
                "Manguerutas para bomba peristaltica",
                "Solenoide 24v",
                "Solenoide 220v",
                "Valvula desagote 51mm",
                "Diafragma de valvula desagote 51mm",
                "MAQUINARIA INDISPENSABLE:",
                "Autogena",
                "Bomba de vacio",
                "Balanza",
                "Dobladoras de caño",
                "Nitrogeno",
                "Manifold",
                "Corta tubo",
                "Accesorios para prueba de panza",
                "Viroladora",
                "Llave para robinetes",
            ]
        },
        {
            id: "equipo_ordene",
            title: "Equipo Ordeñe",
            items: [
                "PARTE VACIO:",
                "Bomba de vacio (según tambo)",
                "Motor electrico (según bomba de vacio)",
                "Polea para motor",
                "Polea para bomba de vacio",
                "Prisioneros",
                "Chavetas",
                "Correas",
                "Aceitera 2 picos - 3 picos",
                "Magueritas para aceitera",
                "Accesorios galvanizados roscados",
                "Valvula antiretono 75pvc",
                "Escape - silenciador",
                "Bulones",
                "Accesorios de goma para admision",
                "PARTE LECHE:",
                "Bomba de leche completa",
                "Sello bomba de leche",
                "Tapa intermedia",
                "Guarnicion",
                "Turbina",
                "Eje",
                "Pico de salida",
                "Placa de refrescado",
                "PARTE PULSADO:",
                "Kit reparacion de pulsadores correspondiente",
                "Pulsador completo",
                "Central de pulsado",
            ]
        },
        {
            id: "electrico",
            title: "Electrico",
            items: [
                "Disyuntor 4 polos",
                "Disyuntor 2 polos",
                "Termicas de 4-3-2-1 polos",
                "Contactor",
                "Relevo termico",
                "Contactos auxiliares",
                "Guardamotor",
                "Timer gt3a con zocalo",
                "Cables unipolar (varias medidas)",
                "Cables tpr (varias medidas)",
                "Rielding",
                "Cablecanal",
                "Cajas estanto",
                "Boton schneider",
                "Maneta schneider",
                "Portalampara",
                "Foco",
                "Reflector",
                "Tubos led",
                "Prensacable",
                "Final de carrera",
                "MAQUINARIA INDISPENSABLE:",
                "Tester",
            ]
        },
        {
            id: "plomeria",
            title: "Plomeria",
            items: [
                "BOMBAS:",
                "Bomba de agua sumergible (según tambo)",
                "Accesorios roscados desde 2\" a 1\"",
                "Accesorios fusion",
                "Llaves de paso varias medidas",
                "Bomba de lavado (según tambo)",
                "Bomba centrifiga (según tambo)",
                "Accesorios roscados para bombas de lavado y centrifuga",
                "Contactor",
                "Relevo termico",
                "Termica",
                "TERMOTANQUE:",
                "Resistencias (según tambo)",
                "Termostato",
                "Contactor",
                "Termicas unipolares",
                "Accesorios para sacar perdidas",
                "Combistato etc-200",
                "MAQUINARIA INDISPENSABLE:",
                "Stinsol totas las medidas",
                "Llave para resistencias",
                "Saca sarro",
                "Teflon",
                "Hidro 3 - sella rosca",
            ]
        }
    ],
    MATERIALS: [
        {
            id: "materiales",
            title: "Materiales en Service",
            items: [
                "TUBOS CORTOS PULSADO:",
                { name: "180", category: "TUBOS CORTOS PULSADO" },
                { name: "IRLANDA - 200", category: "TUBOS CORTOS PULSADO" },
                { name: "LINEA VERDE - NARANJA", category: "TUBOS CORTOS PULSADO" },
                "TUBOS CORTOS DE LECHE",
                "TAPA ACERO HARMONY INOX",
                "COLECTOR COMPLETO CON INOX:",
                { name: "HARMONY NACIONAL", category: "COLECTOR CON INOX" },
                { name: "BOSIO IRLANDA", category: "COLECTOR CON INOX" },
                { name: "CLASIC 300 NACIONAL", category: "COLECTOR CON INOX" },
                { name: "RODEG", category: "COLECTOR CON INOX" },
                "COLECTOR COMPLETO SIN INOX:",
                { name: "HARMONY NACIONAL", category: "COLECTOR SIN INOX" },
                { name: "BOSIO IRLANDA", category: "COLECTOR SIN INOX" },
                { name: "CLASIC 300 NACIONAL", category: "COLECTOR SIN INOX" },
                { name: "RODEG", category: "COLECTOR SIN INOX" },
                "CLIP DE CIERRE DE VACIO",
                "DISTRIBUIDOR DE PULSADO",
                "CASQUILLOS:",
                { name: "HARMONY", category: "CASQUILLOS" },
                { name: "ESTRIADAS", category: "CASQUILLOS" },
                { name: "IRLANDA", category: "CASQUILLOS" },
                { name: "MILENIUM", category: "CASQUILLOS" },
                { name: "PZ 3", category: "CASQUILLOS" },
                { name: "STD 12", category: "CASQUILLOS" },
                { name: "SILICONA", category: "CASQUILLOS" },
                "SELLO DE BOMBA DE LECHE:",
                { name: "RODEG", category: "SELLO BOMBA LECHE" },
                { name: "BOSIO", category: "SELLO BOMBA LECHE" },
                { name: "FMP 110 NACIONAL", category: "SELLO BOMBA LECHE" },
                { name: "FMP 110 DELAVAL", category: "SELLO BOMBA LECHE" },
                { name: "FMP 55 NACIONAL", category: "SELLO BOMBA LECHE" },
                { name: "FMP 55 DELAVAL", category: "SELLO BOMBA LECHE" },
                "GUARNICION DE BOMBA DE LECHE",
                "KIT DE REPARACION DE REGULADOR DE VACIO",
                "KIT DE REPACION DE PULSADORES:",
                { name: "RODEG", category: "KIT PULSADORES" },
                { name: "GEA", category: "KIT PULSADORES" },
                { name: "EP-100 DELAVAL", category: "KIT PULSADORES" },
                { name: "SCR", category: "KIT PULSADORES" },
                "COPAS DE LAVADO - LAVADOR DE PEZONERAS",
                "VELAS - JETTS DE LAVADO",
                "DISTRIBUIDOR DE LAVADO",
                "VALVULA DE DRENAJE DE DISTRIBUIDOR DE LAVADO",
                "VALVULA ANTIRRETORNO 75 PVC",
                "PIOLA DE EXTRACTOR",
                "GANCHO EXTRACTOR ACR-5000 DELAVAL",
                "DIAGRAGMA VALVULA DE CORTE EXTRACTOR:",
                { name: "ACR- 5000 DELAVAL", category: "DIAFRAGMA EXTRACTOR" },
                { name: "HFC DELAVAL", category: "DIAFRAGMA EXTRACTOR" },
                { name: "SCR", category: "DIAFRAGMA EXTRACTOR" },
                "VALVULA DE DRENAJE 3/4 AMARILLA",
                "VACUOMETRO 100MM",
                "TUBOS LED"
            ]
        }
    ],
    FIELD_SERVICE: [
        {
            id: "service_tambo",
            title: "Service en Tambo",
            items: [
                "Cambio de pezoneras",
                "Cambio de tubos cortos pulsado",
                "Cambio de tubos cortos de leche",
                "Cambio de mirillas rotas",
                "Cambio de acrilicos de colector rotos",
                "Cambio de tapa acero inox",
                "Cambio de colector completo con inox",
                "Cambio de colector completo sin inox",
                "Cambio de clip de cierre de vacio",
                "Cambio de distribuitor de pulsado roto",
                "Cambio de casquillos rotos",
                "Cambio de sello a bomba de leche",
                "Cambio de guarnicion a bomba de leche",
                "Cambio de kit de reparacion a regulador de vacio",
                "Cambio de kit de repacion a pulsadores",
                "Cambio de filtros en linea filtrado",
                "Cambio de copas de lavado - lavador de pezoneras",
                "Cambio de velas - jetts de lavado",
                "Cambio de distribuidor de lavado roto",
                "Cambio de valvula de drenaje de distribuidor de lavado",
                "Cambio de valvula antirretorno bomba de vacio 1",
                "Cambio de valvula antirretorno bomba de vacio 2",
                "Cambio de valvula antirretorno bomba de vacio 3",
                "Cambio piola de extractor rotas",
                "Cambio de gancho extractor",
                "Cambio de diagragma valvula de corte extractor",
                "Cambio de valvula de drenaje 3/4 amarilla",
                "Cambio de vacuometro",
                "Cambio de tubos led quemados",
                "Cambios de resistencias quemadas en termotanque",
                "Limpieza de placa intercambiadora de calor",
                "Limpieza de reguladro de vacio",
                "Limpieza de pulsadores que no pasan el chequeo",
                "Limpieza de cañeria de pulsado",
                "Limpieza de tanque de distribuidor de vacio",
                "Limpieza de tanque de reserva de vacio 1",
                "Limpieza de tanque de reserva de vacio 2",
                "Limpieza de tanque de reserva de vacio 3",
                "Limpieza de valvula antirretorno 1",
                "Limpieza de valvula antirretorno 2",
                "Limpieza de valvula antirretorno 3",
                "Limpieza de aceitera de bomba de vacio 1",
                "Limpieza de aceitera de bomba de vacio 2",
                "Limpieza de aceitera de bomba de vacio 3",
                "Limpieza de valvula de drenaje de cañeria de pulsado",
                "Limpieza de acrilicos de equipos estanco que se desarmaron",
                "Limpieza de sarro de termotanque",
                "Chequeo de equipo de ordeñe con pulsografo",
                "Tomar litros de bomba de vacio 1",
                "Tomar litros de bomba de vacio 2",
                "Tomar litros de bomba de vacio 3",
                "Controlar consumo electrico en resistencia de termotanque",
                "Controlar si hay perdida en placa intercambiadora de calor",
                "Controlar funcionamiento de bomba de leche",
                "Controlar tension de correas bomba de vacio 1",
                "Controlar tension de correas bomba de vacio 2",
                "Controlar tension de correas bomba de vacio 3",
            ]
        }
    ]
};
